#!/bin/sh
#
# This file is part of the metrics repository. Copyright (C) 2013 and above Shogun <shogun@cowtech.it>.
# Licensed under the MIT license, which can be found at http://www.opensource.org/licenses/mit-license.php.
#

git clone https://github.com/fhidalgo/metrics.git
ln -s metrics/metric_fu.rb .metrics
cd metrics
sudo cp cvim /usr/local/bin/cvim
sudo chmod a+x /usr/local/bin/cvim
sudo cp cvim.desktop /usr/share/applications/cvim.desktop
sudo update-desktop-database
